
-- Exploring All Objects in the Database
SELECT * FROM INFORMATION_SCHEMA.TABLES

-- Explore All Columns in the Database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'gold.dim_customers'

----------------------------------------------------------------------------------------
-- DIMENSIONS EXPLORATION

SELECT DISTINCT country FROM dbo.[gold.dim_customers]

SELECT DISTINCT category FROM dbo.[gold.dim_products]
SELECT DISTINCT category, subcategory FROM dbo.[gold.dim_products]
SELECT DISTINCT category, subcategory, product_name FROM dbo.[gold.dim_products]
ORDER BY 1,2,3

----------------------------------------------------------------------------------------
-- DATE EXPLORATION

SELECT 
MIN(order_date) AS first_order_date, 
MAX(order_date) AS last_order_date,
DATEDIFF(year, MIN(order_date), MAX(order_date)) AS order_range_in_years,
DATEDIFF(month, MIN(order_date), MAX(order_date)) AS order_range_in_months
FROM dbo.[gold.fact_sales]

-- Finding the youngest and oldest customer
SELECT 
MIN(birthdate) AS oldest_birthdate,
DATEDIFF(year, MIN(birthdate), GETDATE()) AS oldest_age,
MAX(birthdate) AS youngest_birthdate,
DATEDIFF(year, MAX(birthdate), GETDATE()) AS youngest_age
FROM dbo.[gold.dim_customers]

------------------------------------------------------------------------------------------------------
-- MEASURES EXPOLORATION

-- Sales
SELECT SUM(sales_amount) AS total_sales FROM dbo.[gold.fact_sales]

-- How many items are sold
SELECT SUM(quantity) AS total_quantity FROM dbo.[gold.fact_sales]

-- Average selling price
SELECT AVG(price) AS avg_price FROM dbo.[gold.fact_sales]

-- Total number of orders
SELECT COUNT(order_number) AS total_orders FROM dbo.[gold.fact_sales]
-- I don't want to count same orders twice
SELECT COUNT(DISTINCT order_number) AS total_orders FROM dbo.[gold.fact_sales]

-- Total number of products
SELECT COUNT(DISTINCT product_key) AS total_products FROM dbo.[gold.dim_products]

-- Total number of customers
SELECT COUNT(customer_key) AS total_customers FROM dbo.[gold.dim_customers]

-- total number of customers that had placed an order
SELECT COUNT(DISTINCT customer_key) AS total_customers FROM dbo.[gold.fact_sales]



-- REPORT that shows all key metrics
SELECT 'Total Sales' as measure_name, SUM(sales_amount) AS measure_value FROM dbo.[gold.fact_sales]
UNION ALL
SELECT 'Total Quantity', SUM(quantity) FROM dbo.[gold.fact_sales]
UNION ALL
SELECT 'Average Price', AVG(price) FROM dbo.[gold.fact_sales]
UNION ALL
SELECT 'Total Nr. Orders', COUNT(DISTINCT order_number) FROM dbo.[gold.fact_sales]
UNION ALL
SELECT 'Total Nr. Products', COUNT(product_name) FROM dbo.[gold.dim_products]
UNION ALL
SELECT 'Total Nr. Customers', COUNT(customer_key) FROM dbo.[gold.dim_customers]

----------------------------------------------------------------------------------------------------
-- MAGNITUDE ANALYSIS
-- Find total customers by country
SELECT
country,
COUNT(customer_key) AS total_customers
FROM dbo.[gold.dim_customers]
GROUP BY country
ORDER BY total_customers DESC

-- Find total customers by gender
SELECT
gender,
COUNT(customer_key) AS total_customers
FROM dbo.[gold.dim_customers]
GROUP BY gender
ORDER BY total_customers DESC

-- Find total products by category
SELECT
category,
COUNT(product_key) AS total_products
FROM dbo.[gold.dim_products]
GROUP BY category
ORDER BY total_products DESC

-- Average costs in each category
SELECT
category,
AVG(cost) AS avg_costs
FROM dbo.[gold.dim_products]
GROUP BY category
ORDER BY avg_costs DESC

-- Total ravenue generated for each category
SELECT 
p.category,
SUM(f.sales_amount) AS total_ravenue
FROM dbo.[gold.fact_sales] f
LEFT JOIN dbo.[gold.dim_products] p
	ON p.product_key = f.product_key
GROUP BY category
ORDER BY total_ravenue DESC

-- Total ravenue generated by each customer
SELECT 
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_ravenue
FROM dbo.[gold.fact_sales] f
LEFT JOIN dbo.[gold.dim_customers] c
	ON c.customer_key = f.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_ravenue DESC

-- Distribution of sold items across countries
SELECT 
c.country,
SUM(f.quantity) AS total_sold_items
FROM dbo.[gold.fact_sales] f
LEFT JOIN dbo.[gold.dim_customers] c
	ON c.customer_id = f.customer_key
GROUP BY
c.country
ORDER BY total_sold_items DESC

---------------------------------------------------------------------------
-- RANKING ANALYSIS

-- Which 5 products generate the highest ravenue?
SELECT TOP 5
p.product_name,
SUM(f.sales_amount) AS total_ravenue
FROM dbo.[gold.fact_sales] f
LEFT JOIN dbo.[gold.dim_products] p
	ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_ravenue DESC

-- Which are the 5 worst-performing products in terms of sales?
SELECT TOP 5
p.product_name,
SUM(f.sales_amount) AS total_ravenue
FROM dbo.[gold.fact_sales] f
LEFT JOIN dbo.[gold.dim_products] p
	ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_ravenue



-- using the window function
SELECT *
FROM (
	SELECT p.product_name,
	SUM(f.sales_amount) AS total_ravenue,
	ROW_NUMBER() OVER(ORDER BY SUM(f.sales_amount) DESC) AS rank_products
	FROM dbo.[gold.fact_sales] f
	LEFT JOIN dbo.[gold.dim_products] p
		ON p.product_key = f.product_key
	GROUP BY p.product_name) t
WHERE rank_products <=5

-- Top 10 customers who have generated the highest ravenue
SELECT TOP 10
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_ravenue
FROM dbo.[gold.fact_sales] f
LEFT JOIN dbo.[gold.dim_customers] c
	ON f.customer_key = c.customer_key
GROUP BY 
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_ravenue DESC

-- 3 customers with the fewest orders placed
SELECT TOP 3
c.customer_key,
c.first_name,
c.last_name,
COUNT(DISTINCT order_number) AS total_orders_placed
FROM dbo.[gold.fact_sales] f
LEFT JOIN dbo.[gold.dim_customers] c
	ON f.customer_key = c.customer_key
GROUP BY 
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_orders_placed

SELECT product_name
FROM dbo.[gold.dim_products]